In [ ]:
# While we can't provide the actual datasets we provide the sources and the means to generate the grount-truth distributions# In this notebook we generate the ground-truth distributions based on the U.S. city database.# As describd in the paper most datasets require additional datasets/source as a constraint to the distribution# a list of high bike score cities in NJ
# Bike Score	Description
# 90–100	Biker's Paradise
# Daily errands can be accomplished on a bike.
# 70–89	Very Bikeable
# Biking is convenient for most trips.
# 50–69	Bikeable
# Some bike infrastructure.
# 0–49	Somewhat Bikeable
# Minimal bike infrastructure.

#Queries:
# 1) I am making the move to New Jersey. I'm looking for a place with a good bike score.
# 2) We are looking to move to MI. We are looking for a small town.	

# 3) I want to open a coffee bookstore somewhere in Oregon and I'm trying \
# to find the best place to do it. 
# 4) I'm looking for a place with ppl in their 20s or 30s

# 5) hi, I have been looking at moving to Vermont to carry out my career as\
#  a dog trainer. I'm looking for a relatively dense area to open my business

In [2]:
import pandas as pd
file_path = '../us_cities_db/simplemaps_uscitiesv1/uscities.csv'
df = pd.read_csv(file_path)
df

/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/3618992099.py:3: DtypeWarning: Columns (2,7,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,city,city_ascii,city_alt,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,...,poverty,limited_english,commute_time,health_uninsured,veteran,cbsa_fips,cbsa_name,cbsa_metro,csa_fips,csa_name
0,New York,New York,NaN,NY,New York,36081,Queens,36081|36047|36085|36005|36061,Queens|Kings|Richmond|Bronx|New York,40.6943,...,17.2,13.9,41.1,6.7,2.0,35620.0,"New York-Newark-Jersey City, NY-NJ",True,408.0,"New York-Newark, NY-NJ-CT-PA"
1,Los Angeles,Los Angeles,NaN,CA,California,6037,Los Angeles,06037,Los Angeles,34.1141,...,16.6,13.7,31.3,10.6,2.3,31080.0,"Los Angeles-Long Beach-Anaheim, CA",True,348.0,"Los Angeles-Long Beach, CA"
2,Chicago,Chicago,NaN,IL,Illinois,17031,Cook,17031|17043,Cook|DuPage,41.8375,...,16.9,7.9,34.1,9.8,2.9,16980.0,"Chicago-Naperville-Elgin, IL-IN",True,176.0,"Chicago-Naperville, IL-IN-WI"
3,Miami,Miami,NaN,FL,Florida,12086,Miami-Dade,12086,Miami-Dade,25.7840,...,20.0,29.9,28.2,19.0,2.0,33100.0,"Miami-Fort Lauderdale-West Palm Beach, FL",True,370.0,"Miami-Port St. Lucie-Fort Lauderdale, FL"
4,Houston,Houston,NaN,TX,Texas,48201,Harris,48201|48157|48339,Harris|Fort Bend|Montgomery,29.7860,...,19.6,13.5,27.4,24.2,3.6,26420.0,"Houston-Pasadena-The Woodlands, TX",True,288.0,"Houston-Pasadena, TX"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109034,Pennwood,Pennwood,NaN,DE,Delaware,10001,Kent,10001,Kent,39.1273,...,NaN,NaN,NaN,NaN,NaN,20100.0,"Dover, DE",True,428.0,"Philadelphia-Reading-Camden, PA-NJ-DE-MD"
109035,Buckton,Buckton,NaN,NY,New York,36089,St. Lawrence,36089,St. Lawrence,44.7384,...,NaN,NaN,NaN,NaN,NaN,32390.0,"Massena-Ogdensburg, NY",False,NaN,NaN
109036,Millerstown,Millerstown,NaN,PA,Pennsylvania,42013,Blair,42013,Blair,40.2771,...,NaN,NaN,NaN,NaN,NaN,11020.0,"Altoona, PA",True,107.0,"Altoona-Huntingdon, PA"
109037,Hidden Lakes,Hidden Lakes,NaN,OH,Ohio,39117,Morrow,39117,Morrow,40.5479,...,NaN,NaN,NaN,NaN,NaN,18140.0,"Columbus, OH",True,198.0,"Columbus-Marion-Zanesville, OH"
109038,Bancroft,Bancroft,NaN,ME,Maine,23003,Aroostook,23003,Aroostook,45.7020,...,NaN,NaN,NaN,NaN,NaN,12620.0,"Bangor, ME",True,NaN,NaN

In [ ]:
prompt = "I want to open a coffee bookstore somewhere in Oregon and I'm trying \
to find the best place to do it. \
I'm looking for a place with ppl in their 20s or 30s"

In [15]:
df1 = df[df['state_name']=='Oregon']
att = '30_n_20'
df1["30_n_20"] = df1['age_30s']+df1['age_20s']
df1 = df1.sort_values(by=att, ascending=False)
df1.to_csv('../relevant_db/OR_20_n_30.csv')

/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_3100/4214418617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["30_n_20"] = df1['age_30s']+df1['age_20s']

In [ ]:
prompt = "hi, I have been looking at moving to Vermont to carry out my career as a dog trainer.\
      I'm looking for a relatively dense area to open my business" # no info on density

prompt = "hi, I have been looking at moving to Georgia to carry out my career as a dog trainer.\
      I'm looking for a relatively public-transit friendly place to open my business"

In [21]:
df1 = df[df['state_name']=='Georgia']
att = 'density'
df1 = df1.sort_values(by=att, ascending=False)
df1.to_csv('../relevant_db/GA_density.csv')

In [8]:
prompt = "I'm looking to open a high quality bread/pastry bakery in a safe area in Kansas."
df1 = df[df['state_name']=='Kansas']
df1

,city,city_ascii,city_alt,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,...,poverty,limited_english,commute_time,health_uninsured,veteran,cbsa_fips,cbsa_name,cbsa_metro,csa_fips,csa_name
85,Wichita,Wichita,NaN,KS,Kansas,20173,Sedgwick,20173,Sedgwick,37.6895,...,15.5,3.0,18.8,12.3,6.9,48620.0,"Wichita, KS",True,556.0,"Wichita-Arkansas City-Winfield, KS"
235,Overland Park,Overland Park,NaN,KS,Kansas,20091,Johnson,20091,Johnson,38.8870,...,4.2,2.6,19.9,5.2,5.5,28140.0,"Kansas City, MO-KS",True,312.0,"Kansas City-Overland Park-Kansas City, MO-KS"
293,Kansas City,Kansas City,NaN,KS,Kansas,20209,Wyandotte,20209,Wyandotte,39.1235,...,17.4,8.5,21.7,18.1,6.1,28140.0,"Kansas City, MO-KS",True,312.0,"Kansas City-Overland Park-Kansas City, MO-KS"
313,Topeka,Topeka,NaN,KS,Kansas,20177,Shawnee,20177,Shawnee,39.0346,...,16.0,2.6,17.1,9.9,8.1,45820.0,"Topeka, KS",True,NaN,NaN
323,Olathe,Olathe,NaN,KS,Kansas,20091,Johnson,20091,Johnson,38.8833,...,6.1,3.3,21.5,7.3,5.3,28140.0,"Kansas City, MO-KS",True,312.0,"Kansas City-Overland Park-Kansas City, MO-KS"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108990,Lamar,Lamar,NaN,KS,Kansas,20143,Ottawa,20143,Ottawa,39.2561,...,NaN,NaN,NaN,NaN,NaN,41460.0,"Salina, KS",False,NaN,NaN
108993,Winkler,Winkler,NaN,KS,Kansas,20161,Riley,20161,Riley,39.4817,...,NaN,NaN,NaN,NaN,NaN,31740.0,"Manhattan, KS",True,NaN,NaN
108997,Lasita,Lasita,NaN,KS,Kansas,20161,Riley,20161,Riley,39.4089,...,NaN,NaN,NaN,NaN,NaN,31740.0,"Manhattan, KS",True,NaN,NaN
109003,Flush,Flush,NaN,KS,Kansas,20149,Pottawatomie,20149,Pottawatomie,39.2944,...,NaN,NaN,NaN,NaN,NaN,31740.0,"Manhattan, KS",True,NaN,NaN
109005,Ladysmith,Ladysmith,NaN,KS,Kansas,20027,Clay,20027,Clay,39.2714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN

In [12]:
# form a df of those towns
#df2 = df[df['state_name']=='Kansas']
file_path = 'crime_rates_KN_prep.csv'
df2 = pd.read_csv(file_path)

df1 = df1.set_index('city')
df1 = df1.reindex(index=df2['city'])
df1 = df1.reset_index()
df1['crime_index'] = df2['crime index']
#result = df2[condition]
df1.to_csv('../relevant_db/KN_crime_rates.csv')

In [ ]:
prompt = "We are moving to Florida. We are looking for communities who are at their retirement age"

In [22]:
df1 = df[df['state_name']=='Florida']
att = 'age_over_65'
df1 = df1.sort_values(by=att, ascending=False)
df1.to_csv('../relevant_db/FL_age_over_65.csv')

In [ ]:
prompt = "We are planning to move to Ohio. We are looking for an affordable area."
# median household income in Ohio is $67k

In [25]:
df1 = df[df['state_name']=='Ohio']
att = 'between_50k_n_20k'
df1["between_50k_n_20k"] = df1['income_household_35_to_50']+df1['income_household_25_to_35']+df1['income_household_20_to_25']
df1 = df1.sort_values(by=att, ascending=False)
df1.to_csv('../relevant_db/OH_between_50k_n_20k.csv')

/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_3100/4174380229.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["between_50k_n_20k"] = df1['income_household_35_to_50']+df1['income_household_25_to_35']+df1['income_household_20_to_25']

In [26]:
prompt = 'We are looking to move to MI. We are looking for a small town'
# National League of Cities (NLC)
# The NLC categorizes cities and towns based on population size:
# Small City/Town: Typically considered to be those with populations under 25,000.
# Large Town: Population between 25,000 and 75,000.
# City: Population over 75,000.
df1 = df[df['state_name']=='Michigan']
att = 'population_proper'
df1 =  df1[df1['population_proper']< 25000]
df1 = df1.sort_values(by=att, ascending=False)
df1.to_csv('../relevant_db/MI_population_proper.csv')

In [ ]:
# https://www.freemaptools.com/find-cities-and-towns-inside-radius.htm
prompt = "I'm visiting Wisconsin. We are interested in visiting dairy farms."

In [12]:
df1 = df[df['state_name']=='Massachusetts']
df1 = df1[['city', 'lat', 'lng']]
df1
df1.to_csv('../relevant_db/MA_public_transit_scores.csv')

In [26]:
# Tennesee
prompt = "I'm visiting Tennessee. We are interested in visiting places of historical heritage. \
  Can you please recommend to me cities or towns to stay in that are close to good state parks?"
# retrieve the official historical heritage of TN
# extract all towns/cities that are within 3 miles to these ones.

# https://www.tn.gov/historicalcommission/state-programs/state-historic-sites.html

d = {"sites": ["Alex Haley house museum", \
             "parker's crossroad battlefield", \
             "clement railroad hotel museum", \
             "battle of nashville monument",
             "carter state historic site",\
             "the president james k polk home and museum",
             "the sam davis memorial museum",
             "camp blount historic site and museum",\
             "rock castle state historic park",\
             "cragfont state historic park",
             "wynnewood state historic park",
             "Hawthorn hill state historic park",\
             "sparta rock house state historic park",\
             "marble springs state historic site",\
             "sam houston schoolhouse state historic",\
             "chester inne state historic site",\
             "tipton haynes state historic site",\
             "sabine hill state historic site",\
             "rocky mount state historic site",
             "duckton basin museum at burra burra"], \
     "towns": ["Henning", "Wildersville", "Dickson", "Nashville", "Franklin",\
              "Columbia", "Pulaski", "Fayetteville","Hendersonville",\
                "Castalian Springs","Castalian Springs", "Castalian Springs", "Sparta", "Knoxville",\
                    "Maryville", "Jonesborough", "Johnson City", "Elizabethton", "Piney Flats",\
                        "Ducktown"]}
towns = ["Henning", "Wildersville", "Dickson", "Nashville", "Franklin",\
              "Columbia", "Pulaski", "Fayetteville","Hendersonville",\
                "Castalian Springs","Castalian Springs", "Castalian Springs", "Sparta", "Knoxville",\
                    "Maryville", "Jonesborough", "Johnson City", "Elizabethton", "Piney Flats",\
                        "Ducktown"]

In [73]:
import numpy as np
# https://stackoverflow.com/questions/7825956/find-cities-within-given-mile-radius-from-address

df1 = df[df['state_name']=='Tennessee']
df1 = df1[['city', 'lat', 'lng']]
for town in towns:
    first_row = df1.loc[df1['city'] == town].iloc[0]
    town_lat = first_row['lat']
    town_lng = first_row['lng']
    print(town_lat)
    print(town_lng)
    # exctract all towns that are within 3 mile radius
    df1[town] = np.where(((df1.lat-town_lat)**2+(df1.lng-town_lng)**2 < 0.1), 'close', 'not')
    
df1

35.682
-89.577
35.7766
-88.3561
36.0637
-87.3665
36.1715
-86.7842
35.92
-86.8516
35.6238
-87.0484
35.1933
-87.035
35.149
-86.5634
36.3063
-86.5997
36.4012
-86.3067
36.4012
-86.3067
36.4012
-86.3067
35.9347
-85.4726
35.9692
-83.9496
35.7468
-83.9789
36.2959
-82.4766
36.3406
-82.3806
36.3367
-82.237
36.4195
-82.304
35.036
-84.3848

,city,lat,lng,Henning,Wildersville,Dickson,Nashville,Franklin,Columbia,Pulaski,...,Hendersonville,Castalian Springs,Sparta,Knoxville,Maryville,Jonesborough,Johnson City,Elizabethton,Piney Flats,Ducktown
44,Nashville,36.1715,-86.7842,not,not,not,close,close,not,not,...,close,not,not,not,not,not,not,not,not,not
48,Memphis,35.1087,-89.9663,not,not,not,not,not,not,not,...,not,not,not,not,not,not,not,not,not,not
75,Knoxville,35.9692,-83.9496,not,not,not,not,not,not,not,...,not,not,not,close,close,not,not,not,not,not
108,Chattanooga,35.0660,-85.2481,not,not,not,not,not,not,not,...,not,not,not,not,not,not,not,not,not,not
213,Clarksville,36.5692,-87.3413,not,not,not,not,not,not,not,...,not,not,not,not,not,not,not,not,not,not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108972,Elza,36.0526,-84.2030,not,not,not,not,not,not,not,...,not,not,not,close,not,not,not,not,not,not
108989,Red Row,35.5262,-87.1936,not,not,not,not,not,close,not,...,not,not,not,not,not,not,not,not,not,not
108996,Life,35.6145,-88.4787,not,close,not,not,not,not,not,...,not,not,not,not,not,not,not,not,not,not
109021,Imperial Estates,35.9895,-84.0963,not,not,not,not,not,not,not,...,not,not,not,close,close,not,not,not,not,not
109026,Dumplin Mill,35.9973,-83.5635,not,not,not,not,not,not,not,...,not,not,not,not,not,not,not,not,not,not

In [75]:
# form a df of those towns
condition = (df1 == 'close').any(axis=1)
df2 = df[df['state_name']=='Tennessee']
result = df2[condition]
result.to_csv('../relevant_db/TN_historical_sites.csv')

In [ ]:
prompt = "I'm looking to open a high quality bread/pastry bakery in MA that is accessible to public transit (bus/subway/commute rail)"

In [92]:
prompt = "Coming to Arkansas. I’m interested in visiting it’s state parks. \
    Can you please recommend to me cities or towns to stay in that are close to good state parks?"

# https://koordinates.com/layer/102903-arkansas-state-park-state-park-locations/
file_path = '../code/State_Parks_AR.csv'
df3 = pd.read_csv(file_path)

df1 = df[df['state_name']=='Arkansas']

for index, row in df3.iterrows():
    lat = row['lat']
    lng = row['lng']
    df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
    
df1

/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/725247226.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')

,city,city_ascii,city_alt,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,...,20,21,22,23,24,25,26,27,28,29
94,Little Rock,Little Rock,NaN,AR,Arkansas,5119,Pulaski,05119,Pulaski,34.7256,...,not,not,not,not,not,not,not,not,not,not
113,Fayetteville,Fayetteville,NaN,AR,Arkansas,5143,Washington,05143,Washington,36.0714,...,not,not,not,not,not,not,not,not,not,not
364,Fort Smith,Fort Smith,NaN,AR,Arkansas,5131,Sebastian,05131,Sebastian,35.3495,...,not,not,not,not,not,not,not,not,not,not
554,Springdale,Springdale,NaN,AR,Arkansas,5143,Washington,05143|05007,Washington|Benton,36.1901,...,not,not,not,not,not,not,not,not,not,not
622,Jonesboro,Jonesboro,NaN,AR,Arkansas,5031,Craighead,05031,Craighead,35.8212,...,not,not,not,not,not,not,not,not,not,not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108560,Patoka,Patoka,NaN,AR,Arkansas,5035,Crittenden,5035,Crittenden,35.0734,...,not,not,not,not,not,not,not,not,not,not
108683,Muddy Fork,Muddy Fork,NaN,AR,Arkansas,5061,Howard,5061,Howard,34.1359,...,not,not,not,not,not,not,not,not,not,not
108696,Nelsonville,Nelsonville,NaN,AR,Arkansas,5135,Sharp,5135,Sharp,36.0701,...,not,not,not,not,not,not,not,not,not,not
108801,Rhea,Rhea,NaN,AR,Arkansas,5143,Washington,5143,Washington,36.0142,...,not,not,not,not,not,not,not,not,not,not
108802,Rio Vista,Rio Vista,NaN,AR,Arkansas,5145,White,5145,White,35.2906,...,not,not,not,not,not,not,not,not,not,not

In [94]:

# form a df of those towns
condition = (df1 == 'close').any(axis=1)
df2 = df[df['state_name']=='Arkansas']
result = df2[condition]
result
result.to_csv('../relevant_db/AR_state_parks.csv')

In [95]:
# https://www.outdooralabama.com/where-fish-alabama/alabama-public-fishing-lakes-pfls
prompt = "I'm visiting Alabama. I'd like to go to a public fishing lake or pond.\
    I'd like to find a place to stay nearby it."

file_path = '../code/state_public_fishing_ponds_AL.csv'
df3 = pd.read_csv(file_path)

df1 = df[df['state_name']=='Alabama']

for index, row in df3.iterrows():
    lat = row['lat']
    lng = row['lng']
    df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
    
df1

/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_1980/3523039494.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')

,city,city_ascii,city_alt,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,...,10,11,12,13,14,15,16,17,18,19
61,Birmingham,Birmingham,NaN,AL,Alabama,1073,Jefferson,01073|01117,Jefferson|Shelby,33.5279,...,not,not,not,not,not,not,not,not,not,not
122,Huntsville,Huntsville,NaN,AL,Alabama,1089,Madison,01089|01083|01103,Madison|Limestone|Morgan,34.6981,...,not,not,not,not,close,not,not,not,not,not
136,Mobile,Mobile,NaN,AL,Alabama,1097,Mobile,01097,Mobile,30.6782,...,not,not,not,not,not,not,not,not,not,not
182,Montgomery,Montgomery,NaN,AL,Alabama,1101,Montgomery,01101,Montgomery,32.3482,...,not,not,not,not,not,not,not,not,not,not
280,Tuscaloosa,Tuscaloosa,NaN,AL,Alabama,1125,Tuscaloosa,01125,Tuscaloosa,33.2348,...,not,not,not,not,not,not,not,not,not,not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108862,DeArmanville,DeArmanville,NaN,AL,Alabama,1015,Calhoun,1015,Calhoun,33.6265,...,not,not,not,not,not,not,not,not,not,not
108868,Beaty Crossroads,Beaty Crossroads,NaN,AL,Alabama,1049,DeKalb,1049,DeKalb,34.6956,...,not,not,not,not,not,not,not,not,not,not
108871,Stewart,Stewart,NaN,AL,Alabama,1065,Hale,1065,Hale,32.9112,...,not,not,not,not,not,not,not,not,not,not
108952,Baltimore Hill,Baltimore Hill,NaN,AL,Alabama,1089,Madison,1089,Madison,34.8368,...,not,not,not,not,not,not,not,not,not,not
108953,Baltic,Baltic,NaN,AL,Alabama,1109,Pike,1109,Pike,31.6518,...,not,not,not,not,not,not,not,not,not,not

In [97]:
# form a df of those towns
condition = (df1 == 'close').any(axis=1)
df2 = df[df['state_name']=='Alabama']
result = df2[condition]
result
result.to_csv('../relevant_db/AL_public_fishing_ponds.csv')

In [ ]:
prompt = "I'm planning a trip to Wyoming and would love to visit a wildlife habitat area. \
    I'd like to find a place to stay nearby?"
#  https://wgfd.wyo.gov/Public-Access/WHMA

In [14]:
import numpy as np
file_path = '../code/Wildlife_Habitat_management_areas_WY.csv'
df3 = pd.read_csv(file_path)

df1 = df[df['state_name']=='Wyoming']

for index, row in df3.iterrows():
    lat = row['lat']
    lng = row['lng']
    df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
    
df1

/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')
/var/folders/g2/5xxky1ms39j84z1l3vcj2_3m0000gn/T/ipykernel_2678/489518878.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[index] = np.where(((df1.lat-lat)**2+(df1.lng-lng)**2 < 0.05), 'close', 'not')

,city,city_ascii,city_alt,state_id,state_name,county_fips,county_name,county_fips_all,county_name_all,lat,...,30,31,32,33,34,35,36,37,38,39
626,Cheyenne,Cheyenne,NaN,WY,Wyoming,56021,Laramie,56021,Laramie,41.1350,...,not,not,not,not,not,not,not,not,not,not
764,Casper,Casper,NaN,WY,Wyoming,56025,Natrona,56025,Natrona,42.8420,...,not,not,not,not,not,not,not,not,not,not
1515,Gillette,Gillette,NaN,WY,Wyoming,56005,Campbell,56005,Campbell,44.2752,...,not,not,not,not,not,not,not,not,not,not
1584,Laramie,Laramie,NaN,WY,Wyoming,56001,Albany,56001,Albany,41.3099,...,not,not,not,not,not,not,not,not,not,not
2198,Rock Springs,Rock Springs,NaN,WY,Wyoming,56037,Sweetwater,56037,Sweetwater,41.5947,...,not,not,not,not,not,not,not,not,not,not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108575,Fry,Fry,NaN,WY,Wyoming,56025,Natrona,56025,Natrona,42.8675,...,not,not,not,not,not,not,not,not,not,not
108576,Fossil,Fossil,NaN,WY,Wyoming,56023,Lincoln,56023,Lincoln,41.8161,...,not,not,not,not,not,not,not,not,not,not
108577,Foster,Foster,NaN,WY,Wyoming,56009,Converse,56009,Converse,42.6730,...,not,not,not,not,not,not,not,not,not,not
108578,Garrett,Garrett,NaN,WY,Wyoming,56001,Albany,56001,Albany,42.1133,...,not,not,not,not,not,not,not,not,not,not
108610,Mayoworth,Mayoworth,NaN,WY,Wyoming,56019,Johnson,56019,Johnson,43.8319,...,not,not,not,not,not,not,not,not,not,not

In [17]:
# form a df of those towns
condition = (df1 == 'close').any(axis=1)
df2 = df[df['state_name']=='Wyoming']
result = df2[condition]
result
result.to_csv('../relevant_db/WY_wildlife_habitat.csv')